<?php

namespace Database\Seeders;

use App\Models\Organization;
use App\Models\OrganizationSnapshot;
use App\Models\Review;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 1. Создание учетной записи администратора
        $user = User::firstOrCreate(
            ['email' => 'admin@georeviews.local'],
            [
                'name' => 'Администратор',
                'password' => Hash::make('password'),
                'is_admin' => true,
            ]
        );
        if (! $user->is_admin) {
            $user->update(['is_admin' => true]);
        }

        // 2. Создание демонстрационной карточки организации
        $org = Organization::firstOrCreate(
            ['yandex_org_id' => '67037665858'],
            [
                'name' => 'Додо Пицца (Демо-стенд)',
                'url' => 'https://yandex.ru/maps/org/dodo_pizza/67037665858/reviews/',
                'address' => 'Москва, улица Большая Полянка, 30',
                'rating' => 4.90,
                'ratings_count' => 2774,
                'reviews_count' => 1990,
                'sync_status' => 'completed',
                'sync_progress' => 100,
                'last_synced_at' => now(),
            ]
        );
        if ($org->name === 'Додо Пицца') {
            $org->update(['name' => 'Додо Пицца (Демо-стенд)']);
        }

        // 3. Создание реалистичной истории снимков репутации за последние 60 дней для наглядного графика изменений
        $snapshotsData = [
            [
                'rating_before' => 4.68,
                'rating_after' => 4.72,
                'ratings_count_before' => 2120,
                'ratings_count_after' => 2200,
                'reviews_count_before' => 1590,
                'reviews_count_after' => 1650,
                'new_reviews_added' => 60,
                'updated_reviews_count' => 5,
                'snapshot_at' => now()->subDays(60),
            ],
            [
                'rating_before' => 4.72,
                'rating_after' => 4.75,
                'ratings_count_before' => 2200,
                'ratings_count_after' => 2310,
                'reviews_count_before' => 1650,
                'reviews_count_after' => 1715,
                'new_reviews_added' => 65,
                'updated_reviews_count' => 8,
                'snapshot_at' => now()->subDays(50),
            ],
            [
                'rating_before' => 4.75,
                'rating_after' => 4.78,
                'ratings_count_before' => 2310,
                'ratings_count_after' => 2420,
                'reviews_count_before' => 1715,
                'reviews_count_after' => 1780,
                'new_reviews_added' => 65,
                'updated_reviews_count' => 10,
                'snapshot_at' => now()->subDays(40),
            ],
            [
                'rating_before' => 4.78,
                'rating_after' => 4.82,
                'ratings_count_before' => 2420,
                'ratings_count_after' => 2510,
                'reviews_count_before' => 1780,
                'reviews_count_after' => 1835,
                'new_reviews_added' => 55,
                'updated_reviews_count' => 7,
                'snapshot_at' => now()->subDays(30),
            ],
            [
                'rating_before' => 4.82,
                'rating_after' => 4.85,
                'ratings_count_before' => 2510,
                'ratings_count_after' => 2600,
                'reviews_count_before' => 1835,
                'reviews_count_after' => 1890,
                'new_reviews_added' => 55,
                'updated_reviews_count' => 9,
                'snapshot_at' => now()->subDays(20),
            ],
            [
                'rating_before' => 4.85,
                'rating_after' => 4.88,
                'ratings_count_before' => 2600,
                'ratings_count_after' => 2690,
                'reviews_count_before' => 1890,
                'reviews_count_after' => 1945,
                'new_reviews_added' => 55,
                'updated_reviews_count' => 12,
                'snapshot_at' => now()->subDays(10),
            ],
            [
                'rating_before' => 4.88,
                'rating_after' => 4.90,
                'ratings_count_before' => 2690,
                'ratings_count_after' => 2774,
                'reviews_count_before' => 1945,
                'reviews_count_after' => 1990,
                'new_reviews_added' => 45,
                'updated_reviews_count' => 15,
                'snapshot_at' => now()->subDay(),
            ],
        ];

        foreach ($snapshotsData as $item) {
            OrganizationSnapshot::firstOrCreate(
                [
                    'organization_id' => $org->id,
                    'snapshot_at' => $item['snapshot_at'],
                ],
                $item
            );
        }

        // 4. Заполнение демонстрационными отзывами (55 отзывов для полноценной проверки пагинации по 50 на страницу, фильтров и полнотекстового поиска)
        $sampleReviews = [
            [
                'author_name' => 'Александр Смирнов',
                'author_level' => 'Знаток города 8 уровня',
                'rating' => 5,
                'text' => 'Отличная пиццерия! Всегда чисто, уютно, быстро готовят. Додстеры горячие и с хрустящей корочкой. Персонал очень вежливый и приветливый.',
                'published_at' => now()->subHours(3),
                'business_response_text' => 'Александр, спасибо большое за высокую оценку и теплые слова! Всегда рады видеть вас!',
                'business_response_at' => now()->subHours(2),
            ],
            [
                'author_name' => 'Елена В.',
                'author_level' => 'Знаток города 4 уровня',
                'rating' => 5,
                'text' => 'Заказывали доставку в офис. Привезли за 25 минут, пицца горячая, сыр тянется. Морс из черной смородины натуральный и вкусный.',
                'published_at' => now()->subDays(1),
                'business_response_text' => 'Елена, спасибо за отзыв! Очень рады, что обед в офисе удался на славу :)',
                'business_response_at' => now()->subDays(1)->addHours(1),
            ],
            [
                'author_name' => 'Михаил К.',
                'author_level' => 'Знаток города 12 уровня',
                'rating' => 4,
                'text' => 'Хорошее место у метро Полянка. Бывает людно в обеденное время, но столики освобождаются быстро. Кофе приличный.',
                'published_at' => now()->subDays(2),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Ольга Николаева',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 5,
                'text' => 'Любимая пицца Пепперони Фреш! Регулярно заходим сюда с детьми по выходным. Детям очень нравится игровая зона.',
                'published_at' => now()->subDays(3),
                'business_response_text' => 'Ольга, спасибо за доверие всей семьей! Будем ждать вас снова в гости!',
                'business_response_at' => now()->subDays(3)->addHours(2),
            ],
            [
                'author_name' => 'Дмитрий',
                'author_level' => 'Знаток города 3 уровня',
                'rating' => 5,
                'text' => 'Удобное приложение, отслеживание приготовления по камере на кухне — классная фишка. Заказ выдали ровно за 10 минут.',
                'published_at' => now()->subDays(4),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Анна Соколова',
                'author_level' => 'Знаток города 9 уровня',
                'rating' => 5,
                'text' => 'Прекрасное обслуживание! Заказали новинку с трюфельным соусом, очень нежный вкус. В зале играет приятная ненавязчивая музыка.',
                'published_at' => now()->subDays(5),
                'business_response_text' => 'Анна, спасибо за приятный отзыв! Новинка действительно получилась потрясающей!',
                'business_response_at' => now()->subDays(5)->addHours(3),
            ],
            [
                'author_name' => 'Сергей Васильев',
                'author_level' => 'Знаток города 5 уровня',
                'rating' => 4,
                'text' => 'Пицца вкусная, тесто тонкое с хрустящими бортиками. Единственный минус — в зале было немного душновато, кондиционер работал слабо.',
                'published_at' => now()->subDays(6),
                'business_response_text' => 'Сергей, благодарим за обратную связь! Уже отрегулировали климатическую систему в зале.',
                'business_response_at' => now()->subDays(6)->addHours(4),
            ],
            [
                'author_name' => 'Екатерина Морозова',
                'author_level' => 'Знаток города 7 уровня',
                'rating' => 5,
                'text' => 'Брали кофе и сырники на завтрак. Сырники свежие, не жирные, подаются со сгущенкой. Бариста с улыбкой пожелал хорошего дня, поднял настроение!',
                'published_at' => now()->subDays(7),
                'business_response_text' => 'Екатерина, отличный выбор для начала дня! Бариста передадим отдельную благодарность :)',
                'business_response_at' => now()->subDays(7)->addHours(2),
            ],
            [
                'author_name' => 'Иван Петров',
                'author_level' => 'Знаток города 2 уровня',
                'rating' => 3,
                'text' => 'Пицца нормальная, но курьер опоздал на 15 минут от обещанного времени. Хорошо хоть выдали промокод на пиццу за задержку.',
                'published_at' => now()->subDays(8),
                'business_response_text' => 'Иван, приносим извинения за задержку курьера из-за пробок. Наше правило 60 минут действует всегда!',
                'business_response_at' => now()->subDays(8)->addHours(1),
            ],
            [
                'author_name' => 'Мария Кузнецова',
                'author_level' => 'Знаток города 11 уровня',
                'rating' => 5,
                'text' => 'Обожаю Додо за стабильное качество в любом городе. На Полянке всегда идеальная чистота и быстрый сервис.',
                'published_at' => now()->subDays(9),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Алексей Новиков',
                'author_level' => 'Знаток города 15 уровня',
                'rating' => 5,
                'text' => 'Додстер с сыром и ветчиной — лучший перекус в центре города за разумные деньги. Всегда беру здесь перед работой.',
                'published_at' => now()->subDays(10),
                'business_response_text' => 'Алексей, додстер — наша гордость! Спасибо за постоянный выбор!',
                'business_response_at' => now()->subDays(10)->addHours(2),
            ],
            [
                'author_name' => 'Татьяна Федорова',
                'author_level' => 'Знаток города 4 уровня',
                'rating' => 2,
                'text' => 'Забыли положить сырный соус к пицце и салфетки. Сама пицца была теплой, но без соуса бортики суховаты.',
                'published_at' => now()->subDays(11),
                'business_response_text' => 'Татьяна, простите за невнимательность сборщика заказа! Напишите нам в чат приложения, обязательно компенсируем ошибку.',
                'business_response_at' => now()->subDays(11)->addHours(5),
            ],
            [
                'author_name' => 'Роман Белов',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 5,
                'text' => 'Очень просторный ресторан, много розеток, удобно поработать с ноутбуком за чашкой чая. Пицца Четыре сыра выше всяких похвал.',
                'published_at' => now()->subDays(12),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Светлана Ковалева',
                'author_level' => 'Знаток города 8 уровня',
                'rating' => 4,
                'text' => 'Часто заказываем на семейные праздники комбо из 3 пицц. Выгодно и вкусно. Хотелось бы больше овощных позиций в меню.',
                'published_at' => now()->subDays(13),
                'business_response_text' => 'Светлана, спасибо за предложение! Передали пожелание по расширению вегетарианского меню нашим бренд-шефам.',
                'business_response_at' => now()->subDays(13)->addHours(3),
            ],
            [
                'author_name' => 'Павел Орлов',
                'author_level' => 'Знаток города 10 уровня',
                'rating' => 5,
                'text' => 'Заказ оформил через терминал самообслуживания за 30 секунд. Готовность через 8 минут. Быстро, технологично, вкусно.',
                'published_at' => now()->subDays(14),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Юлия Макарова',
                'author_level' => 'Знаток города 5 уровня',
                'rating' => 5,
                'text' => 'Мясная пицца с цыпленком и охотничьими колбасками просто бомба! Сытно и много начинки. Спасибо поварам!',
                'published_at' => now()->subDays(15),
                'business_response_text' => 'Юлия, шеф-повару обязательно передадим ваши добрые слова! Приходите еще!',
                'business_response_at' => now()->subDays(15)->addHours(2),
            ],
            [
                'author_name' => 'Артем Зайцев',
                'author_level' => 'Знаток города 3 уровня',
                'rating' => 1,
                'text' => 'Привезли пиццу, перевернутую в коробке, весь сыр и начинка прилипли к крышке. Настроение испорчено.',
                'published_at' => now()->subDays(16),
                'business_response_text' => 'Артем, искренне просим прощения за неаккуратную доставку курьера! Отправили вам промокод на бесплатную пиццу в приложении.',
                'business_response_at' => now()->subDays(16)->addHours(1),
            ],
            [
                'author_name' => 'Наталья Лебедева',
                'author_level' => 'Знаток города 7 уровня',
                'rating' => 5,
                'text' => 'Очень чисто в санузлах и в обеденном зале. Столы дезинфицируют сразу после гостей. Для меня с маленьким ребенком это главный критерий.',
                'published_at' => now()->subDays(17),
                'business_response_text' => 'Наталья, для нас чистота и безопасность гостей — абсолютный приоритет! Спасибо, что отметили это.',
                'business_response_at' => now()->subDays(17)->addHours(2),
            ],
            [
                'author_name' => 'Андрей Семенов',
                'author_level' => 'Знаток города 4 уровня',
                'rating' => 4,
                'text' => 'Хорошая пицца Баварская. Острая в меру, соус пикантный. Жаль убрали из меню сезонный ягодный пунш.',
                'published_at' => now()->subDays(18),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Дарья Григорьева',
                'author_level' => 'Знаток города 13 уровня',
                'rating' => 5,
                'text' => 'Бруслетики с брусникой и сгущенкой — это любовь с первого кусочка! Берем к чаю постоянно. Дети в восторге.',
                'published_at' => now()->subDays(19),
                'business_response_text' => 'Дарья, спасибо за отзыв! Бруслетики — хит наших десертов :)',
                'business_response_at' => now()->subDays(19)->addHours(4),
            ],
            [
                'author_name' => 'Максим Павлов',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 5,
                'text' => 'Приветливые кассиры, помогли списать бонусы Додо. Заказ отдали горячим и аккуратно упакованным.',
                'published_at' => now()->subDays(20),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Ирина Богданова',
                'author_level' => 'Знаток города 3 уровня',
                'rating' => 3,
                'text' => 'Пицца вкусная, но в чеке пробили лишний напиток. Заметила только дома. Деньги через поддержку вернули, но осадочек остался.',
                'published_at' => now()->subDays(21),
                'business_response_text' => 'Ирина, приносим извинения за техническую накладку при пробитии чека. Рады, что поддержка оперативно помогла.',
                'business_response_at' => now()->subDays(21)->addHours(2),
            ],
            [
                'author_name' => 'Кирилл Воробьев',
                'author_level' => 'Знаток города 9 уровня',
                'rating' => 5,
                'text' => 'Супер пицца Песто! Очень ароматный соус и сочные томаты черри. Однозначно рекомендую попробовать.',
                'published_at' => now()->subDays(22),
                'business_response_text' => 'Кирилл, спасибо за рекомендацию! Соус песто и вправду великолепен!',
                'business_response_at' => now()->subDays(22)->addHours(1),
            ],
            [
                'author_name' => 'Виктория Мельникова',
                'author_level' => 'Знаток города 16 уровня',
                'rating' => 5,
                'text' => 'Заказывали на день рождения ребенка 6 больших пицц. Привезли минута в минуту прямо к началу праздника! Все гости наелись и хвалили.',
                'published_at' => now()->subDays(23),
                'business_response_text' => 'Виктория, поздравляем именинника! Очень рады, что смогли стать частью вашего праздника!',
                'business_response_at' => now()->subDays(23)->addHours(3),
            ],
            [
                'author_name' => 'Денис Тарасов',
                'author_level' => 'Знаток города 8 уровня',
                'rating' => 4,
                'text' => 'Классическая Маргарита на тонком тесте хороша. Сыр моцарелла качественный, правильная тягучая текстура.',
                'published_at' => now()->subDays(24),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Полина Казакова',
                'author_level' => 'Знаток города 5 уровня',
                'rating' => 5,
                'text' => 'Очень уютная атмосфера у окна с видом на Полянку. Приятно посидеть с друзьями вечером за чаем и пиццей.',
                'published_at' => now()->subDays(25),
                'business_response_text' => 'Полина, столик у панорамного окна — любимое место наших гостей! Ждем вас снова!',
                'business_response_at' => now()->subDays(25)->addHours(2),
            ],
            [
                'author_name' => 'Игорь Жуков',
                'author_level' => 'Знаток города 2 уровня',
                'rating' => 2,
                'text' => 'Пицца была едва теплой, сыр застыл. Видимо, курьер нес без термосумки или вез сразу несколько заказов.',
                'published_at' => now()->subDays(26),
                'business_response_text' => 'Игорь, это недопустимо! Все заказы должны доставляться исключительно в термосумках с подогревом. Разберемся с курьером.',
                'business_response_at' => now()->subDays(26)->addHours(3),
            ],
            [
                'author_name' => 'Кристина Ефимова',
                'author_level' => 'Знаток города 7 уровня',
                'rating' => 5,
                'text' => 'Грибная пицца со сметанным соусом великолепна! Тонкое тесто, нежная текстура. Спасибо за качество!',
                'published_at' => now()->subDays(27),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Владислав Степанов',
                'author_level' => 'Знаток города 11 уровня',
                'rating' => 5,
                'text' => 'Отличное соотношение цены и качества. Акции и кэшбэк додо-коинами в приложении очень радуют.',
                'published_at' => now()->subDays(28),
                'business_response_text' => 'Владислав, благодарим за отзыв! Следите за новыми спецпредложениями в приложении :)',
                'business_response_at' => now()->subDays(28)->addHours(1),
            ],
            [
                'author_name' => 'Алина Ильина',
                'author_level' => 'Знаток города 4 уровня',
                'rating' => 4,
                'text' => 'Удобное расположение рядом с метро. В пиковые часы бывает сложно найти свободный столик на четверых.',
                'published_at' => now()->subDays(29),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Егор Котов',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 5,
                'text' => 'Картофель из печи с сырным соусом хрустящий снаружи и мягкий внутри. Порция приличная и не жирная.',
                'published_at' => now()->subDays(30),
                'business_response_text' => 'Егор, мы запекаем картофель в печи без фритюра! Рады, что оценили.',
                'business_response_at' => now()->subDays(30)->addHours(2),
            ],
            [
                'author_name' => 'Вероника Титова',
                'author_level' => 'Знаток города 9 уровня',
                'rating' => 5,
                'text' => 'Очень вкусные десерты — шоколадный фондан тает во рту. И кофе капучино отличной обжарки.',
                'published_at' => now()->subDays(31),
                'business_response_text' => 'Вероника, спасибо за сладкий отзыв! Фондан с жидким центром — настоящий шедевр!',
                'business_response_at' => now()->subDays(31)->addHours(2),
            ],
            [
                'author_name' => 'Никита Фролов',
                'author_level' => 'Знаток города 3 уровня',
                'rating' => 3,
                'text' => 'Заказ ждали около 25 минут, хотя на экране обещали 12 минут. Очередь была большая, повара явно не справлялись.',
                'published_at' => now()->subDays(32),
                'business_response_text' => 'Никита, приносим извинения за увеличенное время ожидания в час пик. Усилили состав смены на кухне.',
                'business_response_at' => now()->subDays(32)->addHours(4),
            ],
            [
                'author_name' => 'Валерия Кудрявцева',
                'author_level' => 'Знаток города 14 уровня',
                'rating' => 5,
                'text' => 'Цыпленок ранч — наша семейная традиция по пятницам. Всегда идеальный баланс чесночного соуса и сочных томатов.',
                'published_at' => now()->subDays(33),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Григорий Куликов',
                'author_level' => 'Знаток города 5 уровня',
                'rating' => 5,
                'text' => 'Часто захожу на обед: кусочек пиццы, напиток и додстер выходят очень сытно и доступно.',
                'published_at' => now()->subDays(34),
                'business_response_text' => 'Григорий, комбо-обеды созданы для быстрого и сытного перекуса! Рады вас кормить!',
                'business_response_at' => now()->subDays(34)->addHours(3),
            ],
            [
                'author_name' => 'Надежда Голубева',
                'author_level' => 'Знаток города 8 уровня',
                'rating' => 5,
                'text' => 'Персонал работает как часы. Зал чистый, подносы убирают оперативно, мусорные станции не переполнены.',
                'published_at' => now()->subDays(35),
                'business_response_text' => 'Надежда, спасибо! Команда ресторана старается поддерживать идеальный порядок каждый день.',
                'business_response_at' => now()->subDays(35)->addHours(1),
            ],
            [
                'author_name' => 'Антон Баранов',
                'author_level' => 'Знаток города 2 уровня',
                'rating' => 1,
                'text' => 'Заказал доставку, курьер перепутал корпус дома и уехал не туда. Пришлось самому выходить на перекресток встречать.',
                'published_at' => now()->subDays(36),
                'business_response_text' => 'Антон, искренне просим прощения за невнимательность курьера при навигации! Провели строгий инструктаж.',
                'business_response_at' => now()->subDays(36)->addHours(2),
            ],
            [
                'author_name' => 'Евгения Пономарева',
                'author_level' => 'Знаток города 7 уровня',
                'rating' => 5,
                'text' => 'Очень удобно, что есть розетки у каждого диванчика. Подзарядила телефон, пока пила чай с маффином.',
                'published_at' => now()->subDays(37),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Олег Комаров',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 4,
                'text' => 'Сырные палочки с чесночным соусом отличные, пицца Чоризо островата, но для любителей пикантного самое то.',
                'published_at' => now()->subDays(38),
                'business_response_text' => 'Олег, Чоризо с халапеньо — выбор с огоньком! Спасибо за честную оценку.',
                'business_response_at' => now()->subDays(38)->addHours(3),
            ],
            [
                'author_name' => 'Лариса Маркова',
                'author_level' => 'Знаток города 10 уровня',
                'rating' => 5,
                'text' => 'Детский мастер-класс по приготовлению пиццы — просто восторг! Ребенок сам раскатал тесто и выложил начинку, выдали диплом пиццамейкера.',
                'published_at' => now()->subDays(39),
                'business_response_text' => 'Лариса, мы обожаем проводить мастер-классы для юных поваров! Приходите к нам на новые кулинарные праздники!',
                'business_response_at' => now()->subDays(39)->addHours(2),
            ],
            [
                'author_name' => 'Вадим Яковлев',
                'author_level' => 'Знаток города 12 уровня',
                'rating' => 5,
                'text' => 'Быстро, вкусно и предсказуемо высокое качество. Додо на Полянке держит высокую планку уже несколько лет подряд.',
                'published_at' => now()->subDays(40),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Софья Попова',
                'author_level' => 'Знаток города 5 уровня',
                'rating' => 5,
                'text' => 'Обожаю пиццу Аррива! Необычный соус бургер и свежий сладкий перец. Рекомендую всем коллегам в офисе.',
                'published_at' => now()->subDays(41),
                'business_response_text' => 'Софья, спасибо огромное! Аррива — настоящий хит среди наших авторских пицц!',
                'business_response_at' => now()->subDays(41)->addHours(4),
            ],
            [
                'author_name' => 'Глеб Тихонов',
                'author_level' => 'Знаток города 4 уровня',
                'rating' => 4,
                'text' => 'Хорошая точка сети. Иногда долго готовят кофе, если один бариста на смене, но напитки качественные.',
                'published_at' => now()->subDays(42),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Ксения Медведева',
                'author_level' => 'Знаток города 8 уровня',
                'rating' => 5,
                'text' => 'Заказ приготовили буквально за 7 минут. Все горячее, упаковка с контрольной пломбой-наклейкой. Безопасно и гигиенично.',
                'published_at' => now()->subDays(43),
                'business_response_text' => 'Ксения, стандарты безопасности и качества упаковки для нас непререкаемы. Спасибо за высокую оценку!',
                'business_response_at' => now()->subDays(43)->addHours(1),
            ],
            [
                'author_name' => 'Тимофей Беляев',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 5,
                'text' => 'Додстер с песто — шикарное обновление классического рецепта. Корочка хрустит, внутри сочная моцарелла и зелень.',
                'published_at' => now()->subDays(44),
                'business_response_text' => 'Тимофей, додстер с песто покорил многих наших гостей! Приятного аппетита!',
                'business_response_at' => now()->subDays(44)->addHours(2),
            ],
            [
                'author_name' => 'Диана Гордеева',
                'author_level' => 'Знаток города 3 уровня',
                'rating' => 2,
                'text' => 'В пицце было слишком мало начинки по сравнению с фото в приложении, одни пустые бортики на треть диаметра.',
                'published_at' => now()->subDays(45),
                'business_response_text' => 'Диана, приносим извинения за несоблюдение стандартов раскатки теста пиццамейкером! Проведем дополнительный контроль качества.',
                'business_response_at' => now()->subDays(45)->addHours(3),
            ],
            [
                'author_name' => 'Арсений Давыдов',
                'author_level' => 'Знаток города 9 уровня',
                'rating' => 5,
                'text' => 'Очень вежливый курьер, поздоровался, пожелал приятного аппетита. Доставка заняла всего 22 минуты. Сервис на 10 из 10.',
                'published_at' => now()->subDays(46),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Милана Борисова',
                'author_level' => 'Знаток города 17 уровня',
                'rating' => 5,
                'text' => 'Заказываем пиццу в офис на дни рождения сотрудников каждую неделю. Ни разу не подвели с доставкой и всегда всё горячее!',
                'published_at' => now()->subDays(47),
                'business_response_text' => 'Милана, спасибо за постоянное корпоративное доверие! Рады радовать ваш коллектив вкусной пиццей!',
                'business_response_at' => now()->subDays(47)->addHours(2),
            ],
            [
                'author_name' => 'Руслан Матвеев',
                'author_level' => 'Знаток города 7 уровня',
                'rating' => 4,
                'text' => 'Пицца 4 сезона — отличный выбор, когда вкусы у компании разные. Каждый нашел свой любимый сектор.',
                'published_at' => now()->subDays(48),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Инна Филиппова',
                'author_level' => 'Знаток города 5 уровня',
                'rating' => 5,
                'text' => 'Спасибо за быструю реакцию поддержки в приложении! Возник вопрос по начислению кэшбэка, оператор ответил за минуту и все разъяснил.',
                'published_at' => now()->subDays(49),
                'business_response_text' => 'Инна, наша служба заботы о клиентах всегда на связи 24/7! Спасибо за теплые слова!',
                'business_response_at' => now()->subDays(49)->addHours(1),
            ],
            [
                'author_name' => 'Матвей Мартынов',
                'author_level' => 'Знаток города 6 уровня',
                'rating' => 5,
                'text' => 'Пепперони как всегда эталонная. Хрустящая корочка, в меру пикантная колбаска, сыр подрумянен безупречно.',
                'published_at' => now()->subDays(50),
                'business_response_text' => 'Матвей, классическая пепперони — абсолютная легенда Додо! Спасибо за лояльность!',
                'business_response_at' => now()->subDays(50)->addHours(2),
            ],
            [
                'author_name' => 'Василиса Романова',
                'author_level' => 'Знаток города 11 уровня',
                'rating' => 5,
                'text' => 'Замечательное светлое помещение с большими панорамными окнами на улицу. Одно из самых комфортных кафе сети в центре Москвы.',
                'published_at' => now()->subDays(51),
                'business_response_text' => null,
                'business_response_at' => null,
            ],
            [
                'author_name' => 'Константин Воронов',
                'author_level' => 'Знаток города 3 уровня',
                'rating' => 3,
                'text' => 'Вкус нормальный, но пицца приехала слегка теплой. Пришлось подогревать кусочки на сковороде.',
                'published_at' => now()->subDays(52),
                'business_response_text' => 'Константин, извините, что не смогли сохранить пиццу обжигающе горячей! Проверяем изоляцию термосумок.',
                'business_response_at' => now()->subDays(52)->addHours(3),
            ],
            [
                'author_name' => 'Таисия Киселева',
                'author_level' => 'Знаток города 8 уровня',
                'rating' => 5,
                'text' => 'Круассаны с шоколадом к утреннему кофе свежайшие, слоеное тесто буквально тает во рту. Спасибо за прекрасное утро!',
                'published_at' => now()->subDays(53),
                'business_response_text' => 'Таисия, свежая выпечка по утрам — залог отличного настроения на весь день! Ждем вас снова!',
                'business_response_at' => now()->subDays(53)->addHours(1),
            ],
            [
                'author_name' => 'Ярослав Виноградов',
                'author_level' => 'Знаток города 13 уровня',
                'rating' => 5,
                'text' => 'Все супер! Лучшая пиццерия в районе станций метро Серпуховская и Полянка. Постоянный клиент уже более 3 лет.',
                'published_at' => now()->subDays(54),
                'business_response_text' => 'Ярослав, благодарим за многолетнюю дружбу и высокую оценку нашего труда! Всегда рады стараться для вас!',
                'business_response_at' => now()->subDays(54)->addHours(2),
            ],
        ];

        foreach ($sampleReviews as $i => $rev) {
            Review::updateOrCreate(
                [
                    'organization_id' => $org->id,
                    'yandex_review_id' => 'sample_seed_rev_'.($i + 1),
                ],
                $rev
            );
        }
    }
}
